CREATE TABLE genre (
id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
tyylilaji varchar(55) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_sv_0900_ai_ci;


INSERT INTO genre (tyylilaji) VALUES
('Ajopeli'),
('Ammunta'),
('Arcade'),
('First Person Action'),
('First Person Shooter'),
('Hack and Slash'),
('Hiiviskelypeli'),
('Inter Active'),
('Karaoke'),
('Kauhu'),
('Kokoelma'),
('Lentopeli'),
('MMORPG'),
('Musiikki'),
('Party Game'),
('Piirustus'),
('Puzzle'),
('Pyöräily'),
('Rail Shooter'),
('Ralli'),
('Ratsastus'),
('Reaaliaikainen Strategiapeli'),
('Rooli'),
('Seikkailu'),
('Selviytymiskauhu'),
('Simulaatio'),
('Strategia'),
('Taistelu'),
('Tanssi'),
('Tappelu'),
('Tasoloikka'),
('Third Person Shooter'),
('Toiminta'),
('Urheilu'),
('Toimintaroolipeli'),
('Tietokilpailu'),
('Oppimispeli'),
('Virtuaalilemmikit');