SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";



--
-- Database: `Pelit`
--

-- --------------------------------------------------------

--
-- Rakenne taululle `pelit`
--

CREATE TABLE `pelit` (
  `pelit_id` int NOT NULL,
  `pelin_nimi` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `tyylilaji` varchar(70) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ikasuositus` int NOT NULL,
  `tunniste` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Vedos taulusta `pelit`
--

INSERT INTO `pelit` VALUES
('Black Manta', 'Seikkailu / Taistelu', 0, 2),
('Captain Comic', 'Seikkailu', 0, 2),
('Chip`n Dale, Rescue Rangers', 'Tasoloikka', 0, 2),
('Double DragonIII', 'Taistelu', 0, 2),
('High Speed, Pinball', 'Urheilu', 0, 2),
('RoboCop', 'Seikkailu', 0, 2),
('Super Mario bros', 'Tasoloikka', 0, 2),
('Super Mario Bros/Duck Hunt', 'Tasoloikka', 0, 2),
('Super Mario Bros3', 'Tasoloikka', 0, 2),
('Super Mario Bros3', 'Tasoloikka', 0, 2),
('Zelda II, the adventure of Link (gold)', 'Seikkailu', 0, 2),
('Cats 2', 'Inter Active', 3, 19),
('Cats', 'Inter Active', 3, 19),
('Guitar Hero On Tour', 'Musiikki', 3, 19),
('Super Mario64', 'Tasoloikka / Seikkailu', 3, 19),
('Tetris DS', 'Puzzle', 3, 19),
('Dragon Ball Z Supersonic Warriors', 'Taistelu', 1, 16),
('Dragon Ball Z Taiketsu', 'Taistelu', 1, 16),
('Dragon Ball Z The Legacy of Goku 2', 'Rooli', 7, 16),
('Dragon Ball Z the Legacy of Goku 2', 'Taistelu', 3, 16),
('DRX Mario 2 Games in 1', 'Puzzle', 3, 16),
('Golden Sun', 'Rooli', 0, 16),
('Mario Power Tennis', 'Urheilu', 3, 16),
('Pokemon Firered Version', 'Rooli', 3, 16),
('Pokemon Saphire Version', 'Rooli', 3, 16),
('Tales of Phantasia', 'Seikkailu', 7, 16),
('The Land Before Time, Into the Mysterious Beyond', 'Seikkailu', 3, 16),
('Alice in Wonderland', 'Tasoloikka / Seikkailu', 3, 15),
('Donkey Kong Country', 'Seikkailu', 3, 15),
('Dragon Ball Z Legendary Super Warriors', 'Rooli', 1, 15),
('Pokemon Tradin Card Game', 'Rooli', 1, 15),
('Pokemon Tradin Card Game', 'Rooli', 3, 15),
('Shadowgate Classic', 'Tasoloikka / Seikkailu', 3, 15),
('Wario Land 3', 'Tasoloikka', 1, 15),
('F1 Pole Position', 'Ajopeli', 8, 14),
('Pokemon Blue Version', 'Rooli', 1, 15),
('Pokemon Red Version', 'Rooli', 3, 15),
('Donkey Konga', 'Musiikki', 3, 5),
('Dragon Ball Z Budokai', 'Taistelu', 3, 5),
('Eternal Darkness Sanity`s Reguiem', 'Toiminta / Seikkailu', 3, 5),
('Harry Potter & The Prisoner of Azkaban', 'Seikkailu', 3, 5),
('Mario Kart Double Dash', 'Ajopeli', 3, 5),
('Mario Party 6', 'Tasoloikka', 7, 5),
('Metroid Prime 2: Echoes', 'First Person Action / Seikkailu', 3, 5),
('Metroid Prime', 'First Person Shooter / Seikailu', 3, 5),
('NBA Courtside 2002', 'Urheilu', 7, 5),
('Pokemon Colosseum', 'Seikkailu', 15, 5),
('Pro Rally', 'Ajopeli', 3, 5),
('Sonic Adventure DX, Director`s cut', 'Tasoloikka', 3, 5),
('Sonic Adventure2 Battle', 'Tasoloikka', 3, 5),
('Sonic Heroes', 'Tasoloikka', 3, 5),
('Spyro aHeroes Tail', 'Toiminta', 3, 5),
('Super Mario Sunshine', 'Seikkailu', 11, 5),
('Super Smash Bros Melee', 'Toiminta', 12, 5),
('Taikaviitta', 'Seikkailu', 3, 5),
('Zelda Collector`s Edition', 'Seikkailu', 3, 5),
('Zelda The Wind Waker', 'Seikkailu', 3, 5),
('Alex Kidd in the Enchanted Castle', 'Tasoloikka', 3, 1),
('Art Alive', 'Piirustus', 0, 1),
('Batman', 'Tasoloikka / Taistelu', 0, 1),
('Double Dragon', 'Tasoloikka / Taistelu', 0, 1),
('Earth Worm Jim', 'Tasoloikka', 3, 1),
('FIFA International Soccer', 'Urheilu', 0, 1),
('Garfield Caught in the act', 'Tasoloikka', 3, 1),
('Jordan vs Bird', 'Urheilu', 0, 1),
('Jungle Strike the Sequel to desert strike', 'Taistelu', 0, 1),
('Mickey Mania', 'Tasoloikka', 3, 1),
('NHL 96', 'Urheilu', 3, 1),
('Road Rash 3', 'Ajopeli', 11, 1),
('Side Pocket', 'Urheilu', 0, 1),
('Sonic & Knuckles', 'Tasoloikka', 3, 1),
('Sonic 3', 'Tasoloikka', 3, 1),
('Sonic 3D, Flickies`Island', 'Tasoloikka', 3, 1),
('Sonic The Hedgehog 2', 'Tasoloikka', 3, 1),
('Sonic the Hedgehog Spinball', 'Tasoloikka', 3, 1),
('Sonic The Hedgehog', 'Tasoloikka', 3, 1),
('Sonic The Hedgehog', 'Tasoloikka', 3, 1),
('Sonic The Hedgehog', 'Tasoloikka', 3, 1),
('SplatterHouse 2', 'Kauhu / Taistelu', 0, 1),
('Street FighterII', 'Tasoloikka / Taistelu', 0, 1),
('Streets of Rage', 'Tasoloikka / Taistelu', 0, 1),
('Terminator 2', 'Taistelu', 0, 1),
('The Incredible HULK', 'Tasoloikka', 0, 1),
('The Lion King', 'Tasoloikka', 3, 1),
('The Revenge of Shinobi', 'Tasoloikka / Taistelu', 0, 1),
('The Simpsons, Bart`s Nightmare', 'Tasoloikka', 0, 1),
('Treasure Land Adventure', 'Tasoloikka', 3, 1),
('Winter Olympics', 'Urheilu', 0, 1),
('1080, snowboarding', 'Urheilu', 3, 4),
('CarmaGeddon', 'Ajopeli', 16, 4),
('CastleVania', 'Rooli / Seikkailu', 11, 4),
('Cruisin USA', 'Ajopeli', 3, 4),
('Dark Rift', 'Taistelu', 15, 4),
('Diddy Kong Racing', 'Ajopeli', 3, 4),
('Doom 64', 'First Person Shooter', 15, 4),
('Duke Nukem 64', 'First Person Shooter', 18, 4),
('Exite Bike', 'Ajopeli', 3, 4),
('F1 Pole Position 64', 'Ajopeli', 3, 4),
('GT 64, Championship Edition', 'Ajopeli', 3, 4),
('Lylat Wars', 'Seikkailu', 3, 4),
('Mario Party 3', 'Party Game', 3, 4),
('Mario Kart 64', 'Ajopeli', 3, 4),
('MRC', 'Ajopeli', 3, 4),
('Nascar99', 'Ajopeli', 3, 4),
('NBA Hang time', 'Urheilu', 3, 4),
('NBA Live 99', 'Urheilu', 8, 4),
('Perfect Dark', 'First Person Shooter', 18, 4),
('PilotWings', 'Seikkailu', 3, 4),
('Pokemon Snap', 'Seikkailu', 3, 4),
('Pokemon Stadium', 'Seikkailu', 3, 4),
('Quake II', 'Taistelu', 18, 4),
('Quake', 'Taistelu / Seikkailu', 18, 4),
('Rugrats Treasure Hunt', 'Tasoloikka', 3, 4),
('Snowboard Kids', 'Urheilu', 3, 4),
('Star Wars, Racer, episodi1', 'Seikkailu', 3, 4),
('Super Mario64', 'Tasoloikka', 3, 4),
('Super Mario64', 'Tasoloikka', 3, 4),
('Turok, Dinosaur hunter', 'Seikkailu', 15, 4),
('Turok2, Seeds of evil', 'Seikkailu', 15, 4),
('War Gods', 'Taistelu', 15, 4),
('Wave race', 'Urheilu', 3, 4),
('Yoshi`s Story', 'Tasoloikka', 3, 4),
('Zelda, Ocarina of time', 'Seikkailu', 3, 4),
('7 Wonders of of the ancient world', 'Puzzle', 3, 12),
('Barbie Super Sports', 'Urheilu', 5, 12),
('Diablo 2', 'Rooli / Seikkailu', 16, 12),
('Guild Wars: Factions', 'Rooli / Toiminta', 12, 12),
('Jewel Quest', 'Puzzle', 3, 12),
('Rise of Nations', 'Reaaliaikainen Strategiapeli', 12, 12),
('Spore', 'Reaaliaikainen Strategiapeli', 12, 12),
('The Elder Scrolls III Morrowind', 'Rooli', 12, 12),
('Alkupolku, Kolmas luokka', 'Inter Active', 7, 13),
('Disney Classics Nalle Puh', 'Inter Active', 4, 13),
('Disney Taikastudio', 'Inter Active', 3, 13),
('Lastenlaulu Staraoke', 'Karaoke', 3, 13),
('Mahtava Matikka Raketti', 'Inter Active', 7, 13),
('Mahtava Matikka Raketti', 'Inter Active', 7, 13),
('Mega Staraoke', 'Karaoke', 3, 13),
('Muumit ja Näkymätön lapsi', 'Inter Active', 3, 13),
('Muumit ja Taikalamppu', 'Inter Active', 3, 13),
('Muumit ja Taikatalvi', 'Inter Active', 3, 13),
('Muumit ja Taikurinhattu', 'Inter Active', 3, 13),
('Muumit Meren Aalloilla', 'Inter Active', 3, 13),
('Muumit Piilosilla', 'Inter Active', 3, 13),
('Starcraft', 'Reaaliaikainen Strategiapeli', 16, 13),
('Starcraft Expansion set', 'Reaaliaikainen Strategiapeli', 16, 13),
('Suomiseikkailu', 'Inter Active', 7, 13),
('Alone in the Dark: The New Nightmare', 'Selviytymiskauhu', 15, 9),
('Burnout 3 Takedown', 'Ajopeli', 3, 9),
('Burnout Revenge', 'Ajopeli', 3, 9),
('Crash of the Titans', 'Toiminta / Seikkailu', 7, 9),
('Crash Tag Team Racing', 'Ajopeli', 7, 9),
('Crash The Wrath of Cortex', 'Tasoloikka', 3, 9),
('Crash TwinSanity', 'Tasoloikka', 3, 9),
('Crescent Suzuki Racing', 'Ajopeli', 3, 9),
('Devil May Cry 3 Special Edition', 'Toiminta', 16, 9),
('Dinosaur Adventure', 'Seikkailu', 3, 9),
('Dragon Ball Z Budokai 2', 'Taistelu', 12, 9),
('Dragon Ball Z Budokai 3', 'Taistelu', 12, 9),
('Dragon Ball Z Budokai Tenkaichi', 'Taistelu', 12, 9),
('Ecco the Dolphin Defender of the Future', 'Seikkailu', 3, 9),
('Final Fantasy X', 'Seikkailu / Taistelu', 11, 9),
('Guitar Hero 2', 'Musiikki', 12, 9),
('Guitar hero 3: Legends of Rock', 'Musiikki', 12, 9),
('Guitar Hero: Rocks the 80`s', 'Musiikki', 12, 9),
('Guitar Hero', 'Musiikki', 12, 9),
('Harry Potter ja Huispauksen MM-Kisat', 'Urheilu', 3, 9),
('Hello Kitty, Roller rescue', 'Seikkailu', 3, 9),
('Hitman 2', 'Toiminta', 15, 9),
('Hitman Contracts', 'Toiminta', 15, 9),
('Horse Adventures, Barbie', 'Seikkailu', 3, 9),
('Lord of The Rings The Fellowship of the Ring', 'Toiminta / Seikkailu', 11, 9),
('Mortal Kombat: Shaolin Monks', 'Toiminta / Seikkailu', 18, 9),
('Narnia The Lion,The Witch & The Wardrobe', 'Seikkailu', 7, 9),
('Ratched: Gladiator', 'Ammunta', 3, 9),
('Ratchet & Clank 3', 'Ammunta', 3, 9),
('Shadow the Hedgehog', 'Toiminta / Seikkailu', 12, 9),
('Singstar, 90s', 'Karaoke', 12, 9),
('Singstar, Legendat', 'Karaoke', 11, 9),
('Singstar, Pop Hits', 'Karaoke', 7, 9),
('Singstar, rocks', 'Karaoke', 12, 9),
('Singstar, Suomi rock', 'Karaoke', 12, 9),
('Singstar, Suomipop', 'Karaoke', 12, 9),
('Sonic Gems Collection', 'Tasoloikka', 3, 9),
('Spyro Enter The Dragonfly', 'Toiminta / Seikkailu', 3, 9),
('SSX 3', 'Urheilu', 7, 9),
('Street Hoops', 'Urheilu', 15, 9),
('Tekken 4', 'Taistelu', 15, 9),
('Tekken 5', 'Taistelu', 12, 9),
('The Jungle Book groove party', 'Tanssi', 3, 9),
('The Legend of Spyro a New Beginning', 'Toiminta / Seikkailu', 7, 9),
('The Sims', 'Simulaatio', 7, 9),
('Whiplash', 'Tasoloikka / Toiminta / Seikkailu', 7, 9),
('Abe`s Odyssee Oddworld', 'Tasoloikka', 11, 7),
('Alien Resurrection', 'Kauhu / Taistelu', 15, 7),
('Barbie Race & Ride', 'Ratsastus', 3, 7),
('Battle Arena Toshinden', 'Taistelu', 3, 7),
('Crash Bandicoot 2, Cortex Strikes Back', 'Tasoloikka', 3, 7),
('Crash Bandicoot 3: Warped', 'Tasoloikka', 3, 7),
('Crash Bandicoot', 'Tasoloikka', 3, 7),
('Crash Team Racing', 'Ajopeli', 3, 7),
('Croc Legend of the Gobbos', 'Tasoloikka', 3, 7),
('Dancing Stage Fever', 'Tanssi', 3, 7),
('Destruction Derby', 'Ajopeli', 3, 7),
('Dino Crisis', 'Third Person Shooter / Seikkailu', 15, 7),
('Disney`s Lilo & Stitch, Paratiisisaaren parhaat', 'Inter Active', 3, 7),
('G-Police Weapons of Justice', 'Taistelu', 11, 7),
('Gran Turismo', 'Ajopeli', 3, 7),
('Grand The Auto', 'Toiminta / Seikkailu', 18, 7),
('Harry Potter ja Viisasten kivi', 'Seikkailu', 3, 7),
('Killzone, demo', 'Taistelu', 15, 7),
('Lego Racers', 'Ajopeli', 3, 7),
('Lego Rock Raiders', 'Seikkailu', 3, 7),
('Lifeforce Tenka', 'Taistelu', 18, 7),
('Monsterit Oy Säikkysaari', 'Tasoloikka', 7, 7),
('NBA Jam Extreme', 'Urheilu', 3, 7),
('NBA Live 97', 'Urheilu', 3, 7),
('NHL 98', 'Urheilu', 3, 7),
('Ötökän elämää', 'Seikkailu', 3, 7),
('Parappa the rapper', 'Musiikki', 3, 7),
('Ridge Racer Type 4', 'Ajopeli', 3, 7),
('Road Rash 3D', 'Ajopeli', 11, 7),
('South Park', 'Tasoloikka', 15, 7),
('Space Jam', 'Urheilu', 3, 7),
('Spyro 2, Gateway to Glimmer', 'Tasoloikka', 3, 7),
('Street Skater', 'Urheilu', 11, 7),
('The King of Fighters 95', 'Taistelu', 15, 7),
('Tobal no.1', 'Taistelu', 15, 7),
('Tomb Raider Chronicles', 'Seikkailu', 11, 7),
('Tomb Raider II', 'Seikkailu', 15, 7),
('Tomb Raider III', 'Seikkailu', 15, 7),
('Tomb Raider The Last Revelation', 'Seikkailu', 11, 7),
('Tomb Raider', 'Seikkailu', 15, 7),
('Tony Hawk`s Pro Skater 2', 'Urheilu', 11, 7),
('Tony Hawk`s Skateboarding', 'Urheilu', 3, 7),
('Track & Field International ', 'Urheilu', 3, 7),
('V-Rally Championship Edition', 'Ralli', 3, 7),
('Wild 9', 'Taistelu', 11, 7),
('Legend', 'Seikkailu / Taistelu', 0, 3),
('Super Mario all stars', 'Tasoloikka', 3, 3),
('Super Mario World', 'Tasoloikka', 3, 3),
('Super R-Type', 'Toiminta', 0, 3),
('Zombies', 'Tasoloikka', 3, 3),
('Battalion Wars 2', 'Reaaliaikainen Strategiapeli', 12, 6),
('Excite Truck', 'Ajopeli', 7, 6),
('Far Cry Vengeance', 'First Person Shooter', 16, 6),
('Guitar Hero Metallica', 'Musiikki', 12, 6),
('Guitar Hero World Tour', 'Musiikki', 12, 6),
('Mario Party 8', 'Party Game', 3, 6),
('Metroid Prime 3: Corruption', 'First Person Action / Seikkailu', 12, 6),
('Monster 4X4 World Circuit', 'Ajopeli', 3, 6),
('Mortal Kombat Armageddon', 'Taistelu', 18, 6),
('Naruto Clash of Ninja Revolution', 'Taistelu', 12, 6),
('Rampage Total Destruction', 'Toiminta', 12, 6),
('Resident Evil The Umbrella Chronicles', 'Rail Shooter', 18, 6),
('Rockband 2', 'Musiikki', 12, 6),
('Sonic and the Secret Rings', 'Toiminta / Seikkailu', 7, 6),
('Soulcalibur Legends', 'Toiminta / Seikkailu', 16, 6),
('Super Mario Galaxy', 'Tasoloikka', 3, 6),
('Super Smash Bros. Braw', 'Taistelu / Toiminta', 12, 6),
('The Legend of Spyro Dawn of the Dragon', 'Toiminta', 7, 6),
('The Legend of Spyro The Eternal Night', 'Toiminta', 7, 6),
('The Legend of Zelda: Twilight Princess', 'Toiminta / Seikkailu', 11, 6),
('Warioware Smooth Moves', 'Party Game', 7, 6),
('Wii Fit', 'Urheilu', 3, 6),
('Wii Play', 'Party Game', 3, 6),
('Wii Sports', 'Urheilu', 7, 6),
('Amped2', 'Urheilu', 3, 10),
('Colin Mcrae rally', 'Ajopeli', 3, 10),
('Crash, Nitro Kart', 'Ajopeli', 11, 10),
('Dark Angel', 'Toiminta / Seikkailu', 11, 10),
('Dead or Alive3', 'Taistelu', 18, 10),
('Doom3, resurrection of evil', 'First Person Shooter / Seikailu', 16, 10),
('Doom3', 'First Person Shooter / Seikailu', 18, 10),
('FarCry Instincts', 'First Person Shooter / Seikailu', 12, 10),
('FlatOut', 'Ajopeli', 3, 10),
('Forza Motorsport', 'Ajopeli', 18, 10),
('Grand theft Auto III', 'Rooli / Seikkailu', 18, 10),
('Grand theft Auto, San Andreas', 'Rooli / Seikkailu', 16, 10),
('Halo 1 ja 2', 'First Person Shooter / Seikailu', 16, 10),
('Halo 2, Multiplayer Map Pack', 'First Person Shooter / Seikailu', 15, 10),
('Halo 2', 'First Person Shooter / Seikailu', 16, 10),
('Halo, combat evolved', 'First Person Shooter / Seikailu', 16, 10),
('Halo, Promotional copy', 'First Person Shooter / Seikailu', 15, 10),
('Hitman 2', 'Third Person Shooter / Seikkailu', 16, 10),
('Hitman Contracts', 'Third Person Shooter / Seikkailu', 18, 10),
('Hitman, Blood maney', 'Third Person Shooter / Seikkailu', 16, 10),
('Judge Dredd, dredd vs death', 'First Person Shooter / Seikailu', 3, 10),
('Le Tour de France', 'Pyöräily', 16, 10),
('Legacy of Kain', 'Toiminta / Seikkailu', 12, 10),
('Metal Arms: Glitch in the System', 'Third Person Shooter', 0, 10),
('Midway Arcade Treasures3', 'Arcade', 3, 10),
('Nascar 06', 'Ajopeli', 11, 10),
('Need for Speed Carbon', 'Ajopeli', 11, 10),
('Neep for Speed', 'Ajopeli', 11, 10),
('Oddworld munch`s oddysee', 'Tasoloikka', 12, 10),
('Pirates of the Caribbean', 'Seikkailu', 0, 10),
('Project Gotham racing', 'Ajopeli', 18, 10),
('Projekt Zero', 'Kauhu', 0, 10),
('RalliSport Challenge', 'Ralli', 15, 10),
('Silent Hill 2', 'Kauhu / Seikkailu', 16, 10),
('Terminator 3', 'First Person Shooter / Seikailu', 12, 10),
('Tomb Raider, Legend', 'Seikkailu', 15, 10),
('Unreal Championship', 'First Person Shooter / Seikailu', 3, 10),
('Assassin`s Creed', 'Rooli / Seikkailu', 18, 11),
('Fable 2', 'Rooli', 15, 11),
('Halo 3', 'Third Person Shooter / Seikkailu', 16, 11),
('Lost Planet Extreme Condition', 'Toiminta / Seikkailu', 16, 11),
('Mirror`s Edge', 'Toiminta / Seikkailu', 16, 11),
('NBA Live 07', 'Urheilu', 3, 11),
('Final Fantasy VIII', 'Rooli', 11, 7),
('Final Fantasy I & II', 'Rooli', 3, 16),
('Pokemon Mystery Dungeon, Red Rescue Team', 'Rooli', 3, 16),
('Pokemon Ruby Version', 'Rooli', 3, 16),
('Golden Sun', 'Rooli', 7, 16),
('Golden Sun 2, The Lost Age', 'Rooli', 7, 16),
('Tony Hawk`s 2 Pro Skater', 'Urheilu', 7, 16),
('NBA JAM 2002', 'Urheilu', 3, 16),
('Pokemon Gold Version', 'Rooli', 3, 15),
('Pokemon Crystal Version', 'Rooli', 3, 15),
('Pokemon Red Version', 'Rooli', 3, 15),
('Pokemon Yellow Version', 'Rooli', 3, 15),
('Pokemon Trading Card Game', 'Rooli', 3, 15),
('Super Mario Bros Deluxe', 'Tasoloikka', 3, 15),
('Dragon Ball Z, Legendary Super Warriors', 'Rooli', 3, 15),
('Donkey Kong Land 2', 'Tasoloikka', 3, 15),
('Boktai 2, Solar Boy Django', 'Rooli', 3, 16),
('ChessMaster', 'Strategia', 0, 2),
('FunFair Party', 'Party Game', 7, 6),
('Guild Wars: Nightfall', 'Rooli / Toiminta', 12, 12),
('Guild Wars: Eye of The North', 'Rooli / Toiminta', 12, 12),
('Columns', 'Puzzle', 3, 1),
('Tomb Raider: Underworld', 'Toiminta / Seikkailu', 16, 6),
('Metal Gear Solid', 'Hiiviskelypeli', 15, 7),
('Metal Gear Solid, Special Missions', 'Hiiviskelypeli', 15, 7),
('Grand Theft Auto 2', 'Toiminta', 18, 7),
('Porsche Challenge', 'Ajopeli', 3, 7),
('Die Hard Trilogy', 'First Person Shooter / Third Person Shooter / Ajopeli', 3, 7),
('Downhill Domination', 'Ajopeli', 12, 9),
('State of Emergency', 'Taistelu', 18, 9),
('The Getaway', 'Toiminta', 18, 9),
('Prätkähiiret', 'Ajopeli / Seikkailu', 11, 9),
('Monster hunter tri', 'Toimintaroolipeli', 16, 6),
('Crysis Maximum Edition', 'First Person Shooter', 16, 12),
('Crysis 2', 'First Person Shooter', 16, 12),
('Duke Nukem Forever', 'First Person Shooter', 18, 12),
('Spyro, Season of Ice', 'Tasoloikka', 3, 16),
('Spyro, Year of the Dragon', 'Tasoloikka', 3, 7),
('Spyro 2, Gateway to Glimmer', 'Tasoloikka', 3, 7),
('Spyro the Dragon', 'Tasoloikka', 3, 7),
('Croc Legend of the Gobbos', 'Tasoloikka', 3, 7),
('Spyro: A Hero´s Tail', 'Tasoloikka', 3, 9),
('Guild Wars Prophecies', 'MMORPG', 12, 12),
('Xenoblade Chronicles', 'Rooli', 12, 6),
('The Legend of Spyro Dawn of the Dragon', 'Toiminta', 7, 21),
('inFamous 2', 'Toiminta / Seikkailu', 16, 21),
('Lost Planet 2', 'Third Person Shooter', 16, 21),
('God of War Collection', 'Toiminta / Seikkailu', 18, 21),
('Final Fantasy XIII', 'Rooli', 16, 21),
('Final Fantasy XIII-2', 'Rooli', 16, 21),
('Hunted: The Demon\´s Forge', 'Toiminta', 18, 21),
('Ninja Gaiden 3', 'Toiminta / Seikkailu / Hack and Slash', 18, 21),
('Guild Wars 2', 'MMORPG', 12, 12),
('Call of Duty: Modern Warfare 3', 'First Person Shooter', 18, 11),
('Forza Motorsport 3', 'Ajopeli', 3, 11),
('Battlefield: Bad Company 2', 'First Person Shooter', 16, 11),
('Sega Superstars Tennis', 'Urheilu', 7, 11),
('Avatar', 'Toiminta', 12, 11),
('Call of Duty: Black Ops', 'First Person Shooter', 18, 11),
('Forza Motorsport 4', 'Ajopeli', 3, 11),
('Lost Planet: Extreme Condition', 'Toiminta', 16, 11),
('Alpha Protocol: The Espionage RPG', 'Rooli', 18, 11),
('Kung Fu Panda', 'Toiminta / Seikkailu', 7, 11),
('Harry Potter and The Deathly Hallows Part 1', 'Toiminta / Seikkailu', 12, 11),
('Assassins Creed: Brotherhood', 'Toiminta / Seikkailu', 18, 11),
('Halo 3', 'First Person Shooter', 16, 11),
('Mirrors Edge', 'Toiminta / Seikkailu', 16, 11),
('Fable 3', 'Rooli', 16, 11),
('Fable 2', 'Rooli', 15, 11),
('Fable', 'Rooli', 16, 10),
('Assassins Creed', 'Toiminta / Seikkailu', 18, 11),
('NBA Live 07', 'Urheilu', 3, 11),
('Final Fantasy XIII-2', 'Rooli', 16, 11),
('Hitman Absolution', 'Hiiviskelypeli', 18, 11),
('Forza Horizon', 'Ajopeli', 12, 11),
('The Elder Scrolls V: Skyrim', 'Rooli', 18, 11),
('Assassins Creed: Revelations', 'Toiminta / Seikkailu', 18, 11),
('Medal of Honor: Warfighter', 'First Person Shooter', 16, 11),
('Perfect Dark Zero', 'First Person Shooter', 16, 11),
('Call of Duty 4: Modern Warfare', 'First Person Shooter', 16, 11),
('Zelda, Majora´s Mask', 'Seikkailu', 3, 4),
('James Bond 007, Blood Stone', 'Third Person Shooter', 16, 19),
('FIFA 10', 'Urheilu', 3, 19),
('Garfield´s Nightmare', 'Tasoloikka', 7, 19),
('Lara Groft Tomb Raider, Legend', 'Toiminta / Seikkailu', 12, 19),
('Littlest Pet Shop, Country Friends', 'Simulaatio', 3, 19),
('Tetris DS', 'Puzzle', 3, 19),
('Travel Games For Dummies', 'Puzzle', 3, 19),
('World of Zoo', 'Simulaatio', 3, 19),
('Dr. Mario & Puzzle League', 'Puzzle', 0, 16),
('Mario Power Tennis', 'Urheilu', 3, 16),
('NES Classics Metroid', 'Toiminta / Seikkailu', 3, 16),
('Spyro, Season of Ice', 'Tasoloikka', 0, 16),
('Tales of Phantasia', 'Rooli', 7, 16),
('The Land Before Time, Into the Mysterious Beyond', 'Toiminta', 0, 16),
('Wario Land 4', 'Tasoloikka', 0, 16),
('Alice in Wonderland', 'Tasoloikka', 3, 15),
('Donkey Kong Country', 'Tasoloikka', 0, 15),
('Shadowgate Classic', 'Rooli', 0, 15),
('Donkey Kong Jet Race', 'Ajopeli', 3, 6),
('Funfair party', 'Inter Active', 7, 6),
('Madden NFL 08', 'Urheilu', 0, 6),
('Metroid, Other M', 'Toiminta / Seikkailu', 16, 6),
('NBA 2K13', 'Urheilu', 0, 6),
('Neopets Puzzle Adventure', 'Puzzle', 0, 6),
('Super Paper Mario', 'Tasoloikka / Rooli', 0, 6),
('Buffy the Vampire Slayer, Chaos Bleeds', 'Tappelu', 16, 5),
('Future Tactics, The Uprising', 'Ammunta', 3, 5),
('James Bond 007, Agent Under Fire', 'First Person Shooter', 11, 5),
('Mario Party 5', 'Party Game', 3, 5),
('Mario Party 6', 'Party Game', 3, 5),
('Metroid Prime 2, Echoes', 'First Person Action / Seikkailu', 12, 5),
('NBA Courtside 2002', 'Urheilu', 3, 5),
('NHL 2004', 'Urheilu', 12, 5),
('NHL Hitz 2003', 'Urheilu', 3, 5),
('Mario Party 4', 'Party Game', 3, 5),
('Piglet´s Big Game', 'Toiminta / Seikkailu', 3, 5),
('Sonic Adventure 2, Battle', 'Tasoloikka', 3, 5),
('Sonic Adventure DX, Director´s Cut', 'Tasoloikka / Toiminta / Seikkailu', 3, 5),
('Spyro: A Hero´s Tail', 'Tasoloikka', 3, 5),
('Star Wars: The Clone Wars', 'Toiminta', 11, 5),
('Super Mario Sunshine', 'Tasoloikka / Toiminta / Seikkailu', 3, 5),
('Taikaviitta, Platyrhynchos Kineticus', 'Tasoloikka / Toiminta / Seikkailu', 3, 5),
('100% Star', 'Musiikki', 3, 7),
('007 Tomorrow Never Dies', 'Third Person Shooter / Hiiviskelypeli', 16, 7),
('40 Winks: Conquer Your Dreams', 'Tasoloikka', 3, 7),
('Alien Resurrection', 'First Person Shooter / Selviytymiskauhu', 15, 7),
('ATV Quad Power Racing', 'Ralli', 3, 7),
('Batman Gotham City Racer', 'Ajopeli', 3, 7),
('Castrol Honda Superbike Racing', 'Ajopeli', 3, 7),
('BUST-A-MOVE Arcade 2 Edition', 'Puzzle', 3, 7),
('Colin McRae Rally', 'Ralli', 3, 7),
('Command & Conquer Red Alert', 'Reaaliaikainen Strategiapeli', 12, 7),
('Crash Bash', 'Party Game', 3, 7),
('Dave Mirra Freestyle BMX', 'Urheilu', 3, 7),
('Disney`s Action Game Featuring Hercules', 'Tasoloikka', 3, 7),
('Driver 2', 'Ajopeli / Toiminta', 12, 7),
('E.T.: Interplanetary Mission', 'Puzzle', 3, 7),
('Fifa Football 2004', 'Urheilu', 3, 7),
('Fifa Football 2005', 'Urheilu', 3, 7),
('Football Manager 2000', 'Urheilu', 3, 7),
('Formula One 2001', 'Ajopeli', 3, 7),
('Formula One 99', 'Ajopeli', 3, 7),
('Formula1', 'Ajopeli', 3, 7),
('Formula1, 97', 'Ajopeli', 3, 7),
('Freestyle Scooter', 'Urheilu', 3, 7),
('G-Police: Weapons of Justice', 'Ammunta', 12, 7),
('Gran Turismo 2', 'Ajopeli', 3, 7),
('Haluatko Miljonääriksi', 'Tietokilpailu', 3, 7),
('Harry Potter ja Salaisuuksien Kammio', 'Toiminta / Seikkailu', 3, 7),
('In Cold Blood', 'Seikkailu', 15, 7),
('Jeremy McGranth Supercross 2000', 'Ajopeli', 3, 7),
('King of Bowling 2', 'Urheilu', 3, 7),
('Largo Winch Commando Sar', 'Toiminta / Seikkailu', 13, 7),
('London Racer', 'Ajopeli', 3, 7),
('Mega Man X5', 'Tasoloikka', 3, 7),
('Michael Schumacher Racing World Kart 2002', 'Ajopeli', 3, 7),
('International Moto X', 'Ajopeli', 3, 7),
('Nascar 2000', 'Ajopeli', 3, 7),
('Nascar 99', 'Ajopeli', 3, 7),
('Nascar 98', 'Ajopeli', 3, 7),
('NHL 2000', 'Urheilu', 3, 7),
('NHL 99', 'Urheilu', 3, 7),
('No Fear Downhill Mountain Biking', 'Urheilu', 3, 7),
('Oddworld: Abe`s Oddysee', 'Tasoloikka', 12, 7),
('ONE', 'Third Person Shooter', 13, 7),
('Overblood 2', 'Toiminta / Seikkailu', 15, 7),
('Psybadek', 'Tasoloikka', 3, 7),
('Tom Clancy`s Rainbow Six', 'Ammunta', 15, 7),
('Resident Evil 2', 'Selviytymiskauhu', 18, 7),
('Rollcage', 'Ajopeli', 3, 7),
('Shockwave Assault', 'Lentopeli', 3, 7),
('Soviet Strike', 'Ammunta', 13, 7),
('Spec Ops: Covert Assault', 'Ammunta', 13, 7),
('Spice World', 'Musiikki', 3, 7),
('Star Wars Episode 1: The Phantom Menace', 'Toiminta / Seikkailu', 13, 7),
('Tekken 2', 'Tappelu', 13, 7),
('Tekken 3', 'Tappelu', 13, 7),
('Test Drive 4', 'Ajopeli', 3, 7),
('The Dalmatians', 'Puzzle', 3, 7),
('The Powerpuff Girls: Chemical X-traction', 'Taistelu', 3, 7),
('Tiger Woods 99', 'Urheilu', 3, 7),
('Toca Touring Car Championship', 'Ajopeli', 11, 7),
('Toca World Touring Cars', 'Ajopeli', 11, 7),
('Tony Hawk`s Pro Skateboarding', 'Urheilu', 13, 7),
('Tony Hawk`s Pro Skater 3', 'Urheilu', 3, 7),
('Tony Hawk`s Pro Skater 4', 'Urheilu', 11, 7),
('UEFA Challenge', 'Urheilu', 3, 7),
('V-rally 2', 'Ralli', 3, 7),
('Viper', 'Toiminta', 3, 7),
('Wild Rapids', 'Urheilu', 3, 7),
('Wipeout', 'Ajopeli', 3, 7),
('World´s Scariest Police Chases', 'Ajopeli', 11, 7),
('Wreckin Crew', 'Ajopeli', 13, 7),
('Dungeon Siege 3', 'Toiminta / Seikkailu', 16, 21),
('F1 Championship Edition', 'Ajopeli', 3, 21),
('FIFA 13', 'Urheilu', 3, 21),
('God of War', 'Toiminta / Seikkailu / Hack and Slash', 18, 21),
('Gran Turismo 5 Academy Edition', 'Ajopeli', 3, 21),
('Gran Turismo 5 Prologue', 'Ajopeli', 3, 21),
('Gran Turismo 6', 'Ajopeli', 3, 21),
('Killzone 2', 'First Person Shooter', 18, 21),
('Killzone 3', 'First Person Shooter', 18, 21),
('Le Tour de France', 'Pyöräily', 3, 21),
('LittleBigPlanet 2', 'Tasoloikka', 7, 21),
('Medal of Honor Dice', 'First Person Shooter', 18, 21),
('NHL 11', 'Urheilu', 16, 21),
('NHL 12', 'Urheilu', 16, 21),
('Pro Evolution Soccer 2010', 'Urheilu', 3, 21),
('Racket Sports', 'Urheilu', 3, 21),
('Resistance 2', 'First Person Shooter', 18, 21),
('Resistance 3', 'First Person Shooter', 18, 21),
('Supercar Challenge', 'Ajopeli', 3, 21),
('Uncharted 2: Among Thieves', 'Toiminta / Seikkailu', 16, 21),
('Uncharted 3: Drake´s Deception', 'Toiminta / Seikkailu', 16, 21),
('Virtual Tennis 2009', 'Urheilu', 3, 21),
('007: From Russian with Love', 'Third Person Shooter', 16, 22),
('2006 FIFA World Cup', 'Urheilu', 3, 22),
('ATV Offroad Fury Pro', 'Ajopeli', 3, 22),
('Boog & Elliot', 'Seikkailu / Toiminta', 3, 22),
('Buzz Master Quiz', 'Tietokilpailu', 7, 22),
('Cars 2', 'Ajopeli', 7, 22),
('Diner Dash', 'Strategia', 3, 22),
('Echochrome', 'Puzzle', 3, 22),
('Eragon', 'Toiminta / Seikkailu / Hack and Slash', 16, 22),
('Everybody`s Golf', 'Urheilu', 3, 22),
('Everybody`s Golf 2', 'Urheilu', 3, 22),
('Everybody`s Tennis', 'Urheilu', 3, 22),
('FIFA 10', 'Urheilu', 3, 22),
('Gangs of London', 'Toiminta / Seikkailu', 18, 22),
('Geronimo Stiltonin the Kingdom of Fantasy', 'Seikkailu', 3, 22),
('Ghostbusters', 'Toiminta / Seikkailu / Third Person Shooter', 7, 22),
('God of War', 'Toiminta / Seikkailu / Hack and Slash', 18, 22),
('Gran Turismo', 'Ajopeli', 3, 22),
('Grand Theft Auto Chinatown Wars', 'Toiminta / Seikkailu', 18, 22),
('Grand Theft Auto Liberty City Stories', 'Toiminta / Seikkailu', 18, 22),
('Grand Theft Auto Vice City Stories', 'Toiminta / Seikkailu', 18, 22),
('Hanna Montana Rock Out Show', 'Musiikki', 3, 22),
('Harry Potter ja Liekehtivä Pikari', 'Toiminta / Seikkailu', 7, 22),
('Jak and Daxter Kadonnut Maailma', 'Tasoloikka', 12, 22),
('Killzone: Liberation', 'Ammunta', 16, 22),
('King Kong', 'Toiminta / Seikkailu / First Person Shooter', 12, 22),
('Lego Batman', 'Toiminta / Seikkailu', 7, 22),
('LEGO Indiana Jones 2', 'Toiminta / Seikkailu', 7, 22),
('Little Big Planet', 'Tasoloikka', 7, 22),
('LocoRoco', 'Tasoloikka', 3, 22),
('MediEvil Resurrection', 'Toiminta / Seikkailu / Hack and Slash', 7, 22),
('Mega Minis Volume 1', 'Seikkailu', 12, 22),
('Mega Minis Volume 2', 'Seikkailu', 12, 22),
('Mega Minis Volume 3', 'Seikkailu', 12, 22),
('ModNation Racers', 'Ajopeli', 3, 22),
('Monster Jam Urban Assault', 'Ajopeli', 3, 22),
('Motorstorm Arctic Edge', 'Ajopeli', 12, 22),
('Need for Speed: Carbon Own the City', 'Ajopeli', 12, 22),
('Patapon', 'Musiikki', 7, 22),
('Patapon 2', 'Musiikki', 7, 22),
('Pursuit Force', 'Third Person Shooter / Hiiviskelypeli', 12, 22),
('Pursuit Force: Extreme Justice', 'Taistelu', 12, 22),
('Ratchet & Clank: Size Matters', 'Tasoloikka', 7, 22),
('Resistance: Retribution', 'Third Person Shooter', 16, 22),
('Ridge Racer', 'Ajopeli', 3, 22),
('Ridge Racer 2', 'Ajopeli', 3, 22),
('Secret Agent Clank', 'Tasoloikka', 7, 22),
('Sims 2: Castaway', 'Simulaatio', 12, 22),
('Smash Court Tennis 3', 'Urheilu', 3, 22),
('SOCOM U.S. Navy SEALs Fireteam Bravo', 'Third Person Shooter', 16, 22),
('SoulCalibur: Broken Destiny', 'Taistelu', 16, 22),
('SpongeBob Squarepants: The Yellow Avenger', 'Tasoloikka / Seikkailu', 7, 22),
('TOCA Race Driver 3 Challenge', 'Ajopeli', 3, 22),
('Wipeout Pulse', 'Ajopeli', 3, 22),
('Wipeout Pure', 'Ajopeli', 3, 22),
('World Snooker Challenge 2007', 'Urheilu', 3, 22),
('WRC', 'Ralli', 3, 22),
('Lumines Puzzle Fusion', 'Puzzle', 3, 22),
('James Bond 007: Nightfire', 'First Person Shooter', 12, 9),
('2002 Fifa World Cup', 'Urheilu', 3, 9),
('24: The Game', 'Third Person Shooter', 16, 9),
('Aarreplaneetta', 'Toiminta / Seikkailu', 3, 9),
('Alias', 'Toiminta / Seikkailu', 12, 9),
('Alone in the Dark ', 'Selviytymiskauhu', 18, 9),
('Alpine Ski Racing 2007', 'Urheilu', 12, 9),
('Athens 2004', 'Urheilu', 3, 9),
('Autot', 'Ajopeli / Seikkailu', 3, 9),
('Barbie Horse Adventures: Wild Horse Rescue', 'Seikkailu', 3, 9),
('Batman Begins', 'Hiiviskelypeli', 16, 9),
('Battlefield 2: Modern Combat', 'First Person Shooter', 12, 9),
('Blade II', 'Toiminta', 15, 9),
('Bloodrayne', 'Toiminta / Hack and Slash', 15, 9),
('Bratz: Rock Angelz', 'Seikkailu', 3, 9),
('Buzz! Hollywood Leffavisa', 'Party Game', 12, 9),
('Buzz! Junior: Jungle Party', 'Party Game', 3, 9),
('Buzz! Junior: Monsters Rumble', 'Party Game', 3, 9),
('Buzz! Sporttivisa', 'Party Game', 3, 9),
('Buzz!: Suomen Neropatti', 'Tietokilpailu', 12, 9),
('Call of Duty: Finest Hour', 'First Person Shooter', 16, 9),
('Call of Duty 2: Big Red One', 'First Person Shooter', 16, 9),
('Cabela´s Big Game Hunter', 'Toiminta', 16, 9),
('Centre Court HardHitter', 'Urheilu', 3, 9),
('Colin McRae Rally 3', 'Ajopeli', 3, 9),
('Conflict Global Storm', 'Ammunta', 16, 9),
('Crash Bandicoot: The Wrath of Cortek', 'Tasoloikka', 3, 9),
('Crash: Mind over Mutant', 'Tasoloikka', 3, 9),
('Crash Nitro Kart', 'Ajopeli', 3, 9),
('Crazy Frog Racer', 'Ajopeli', 3, 9),
('Crescent Suzuki Racing', 'Ajopeli', 3, 9),
('Cue Academy; Snooker, Pool, Billiards', 'Urheilu', 3, 9),
('Curious George', 'Tasoloikka', 3, 9),
('Digimon Rumble Arena 2', 'Taistelu', 12, 9),
('Disney Princess', 'Toiminta / Seikkailu', 3, 9),
('Cars Mater-National Championship', 'Ajopeli', 3, 9),
('WALL-E', 'Tasoloikka', 3, 9),
('Disney`s Peter Pan The Legend of NeverLand', 'Toiminta', 3, 9),
('Dogz', 'Seikkailu', 3, 9),
('Dr. Dolittle', 'Simulaatio', 3, 9),
('Driver 3', 'Ajopeli', 16, 9),
('Everybody´s Golf', 'Urheilu', 3, 9),
('Everybody´s Tennis', 'Urheilu', 3, 9),
('F1 04', 'Ajopeli', 3, 9),
('FIFA 06', 'Urheilu', 3, 9),
('FIFA 07', 'Urheilu', 3, 9),
('FIFA 08', 'Urheilu', 3, 9),
('FIFA 09', 'Urheilu', 3, 9),
('FIFA 2001', 'Urheilu', 3, 9),
('FIFA Street', 'Urheilu', 3, 9),
('FIFA Street 2', 'Urheilu', 3, 9),
('Fight Night Round 2', 'Urheilu', 12, 9),
('Final Fantasy X-2', 'Rooli', 12, 9),
('Final Fantasy XII', 'Rooli', 16, 9),
('Flushed Away', 'Toiminta / Seikkailu', 3, 9),
('Formula One 2001 ', 'Ajopeli', 3, 9),
('From Russia With Love', 'First Person Shooter', 16, 9),
('God of War II', 'Toiminta / Hack and Slash', 16, 9),
('Gran Turismo 3 A-spec', 'Ajopeli', 3, 9),
('Gran Turismo 4', 'Ajopeli', 3, 9),
('Gran Turismo Concept: 2002 Tokyo-Geneva', 'Ajopeli', 3, 9),
('Grand Theft Auto 3', 'Toiminta / Seikkailu', 18, 9),
('Grand Theft Auto: Liberty City Stories', 'Toiminta / Seikkailu', 18, 9),
('Grand Theft Auto: San Andreas', 'Toiminta / Seikkailu', 18, 9),
('Grand Theft Auto: Vice City', 'Toiminta / Seikkailu', 18, 9),
('Guitar Hero: World Tour', 'Musiikki', 12, 9),
('Harry Potter ja Feeniksin Kilta', 'Toiminta / Seikkailu', 7, 9),
('Harry Potter ja Salaisuuksien Kammio', 'Toiminta / Seikkailu', 3, 9),
('Heroes of the Pacific', 'Simulaatio', 12, 9),
('Hits Demo', 'Kokoelma', 3, 9),
('Home Alone', 'Toiminta', 3, 9),
('Horsez Ranch Rescue', 'Seikkailu', 3, 9),
('Hugo Bukkazoom', 'Ajopeli', 3, 9),
('Hugo: Peikkometsän Taika', 'Tasoloikka', 3, 9),
('Indiana Jones and the Staff of Kings', 'Toiminta', 16, 9),
('Jak II: Renegade', 'Tasoloikka / Toiminta / Seikkailu', 12, 9),
('Jak and Daxter the Precursor Legacy', 'Tasoloikka', 3, 9),
('Killzone', 'First Person Shooter', 16, 9),
('Le Mans 24 hours', 'Ajopeli', 3, 9),
('Leaderboard Golf', 'Urheilu', 3, 9),
('LEGO Batman: The Video Game', 'Toiminta / Seikkailu', 7, 9),
('LEGO Indiana Jones: The Original Adventures', 'Toiminta / Seikkailu', 3, 9),
('LEGO Star Wars II: The Original Trilogy', 'Toiminta / Seikkailu', 3, 9),
('Leisure Suit Larry: Magna Cum Laude', 'Seikkailu', 18, 9),
('Madden NFL 2001', 'Urheilu', 3, 9),
('Madden NFL 2002', 'Urheilu', 3, 9),
('Medal of Honor: Frontline', 'First Person Shooter', 16, 9),
('MotoGP 4', 'Ajopeli', 3, 9),
('MotorStorm: Arctic Edge', 'Ajopeli', 12, 9),
('Naruto: Ultimate Ninja 3', 'Taistelu', 12, 9),
('NBA 08', 'Urheilu', 3, 9),
('NBA 2K12', 'Urheilu', 12, 9),
('Need for Speed: Carbon', 'Ajopeli', 12, 9),
('Need for Speed: Most Wanted', 'Ajopeli', 3, 9),
('Need for Speed: ProStreet', 'Ajopeli', 3, 9),
('Need for Speed :Undercover', 'Ajopeli', 12, 9),
('Need for Speed: Underground 2', 'Ajopeli', 3, 9),
('New York Race', 'Ajopeli', 3, 9),
('NHL 07', 'Urheilu', 3, 9),
('NHL 08', 'Urheilu', 7, 9),
('NHL 09', 'Urheilu', 7, 9),
('NHL 2002', 'Urheilu', 3, 9),
('NHL 2003', 'Urheilu', 11, 9),
('NHL 2K3', 'Urheilu', 3, 9),
('NHL2K8', 'Urheilu', 16, 9),
('Off Road Extreme! Special Edition', 'Ajopeli', 3, 9),
('PES 2008: Pro Evolution Soccer', 'Urheilu', 3, 9),
('PES 2011: Pro Evolution Soccer', 'Urheilu', 3, 9),
('PES 6: Pro Evolution Soccer', 'Urheilu', 3, 9),
('PES 6: Pro Evolution Soccer', 'Urheilu', 3, 9),
('Pirates of the Caribbean: At World´s End', 'Toiminta / Seikkailu / Hack and Slash', 12, 9),
('Pitfall: The Lost Expedition', 'Toiminta / Tasoloikka', 3, 9),
('Pro Evolution Soccer', 'Urheilu', 3, 9),
('Pro Evolution Soccer 5', 'Urheilu', 3, 9),
('Ratchet & Clank 2: Going Commando', 'Tasoloikka', 3, 9),
('Ratchet & Clank: Size Matters', 'Tasoloikka', 7, 9),
('Rayman 3: Hoodlum Havoc', 'Tasoloikka', 3, 9),
('Rayman Revolution', 'Tasoloikka', 3, 9),
('Ridge Racer V', 'Ajopeli', 3, 9),
('RTL Biathlon 2007', 'Urheilu', 3, 9),
('Sega Mega Drive Collection', 'Kokoelma', 12, 9),
('Shark Tale Hajar Som Hajar', 'Toiminta / Seikkailu', 3, 9),
('Singstar Pop', 'Musiikki', 3, 9),
('Singstar Pop Hits', 'Musiikki', 7, 9),
('ski racing 2006: Featuring Kalle Palander', 'Urheilu', 3, 9),
('SLY 2: Konnakopla', 'Tasoloikka / Hiiviskely', 3, 9),
('SLY 3', 'Tasoloikka / Hiiviskely', 3, 9),
('Sly Raccoon', 'Tasoloikka / Hiiviskely', 3, 9),
('Smarties: Meltdown', 'Tasoloikka / Toiminta / Seikkailu', 3, 9),
('SOCOM 3: U.S. Navy Seals', 'Third Person Shooter', 16, 9),
('Sonic Gems Collection', 'Tasoloikka', 3, 9),
('Sonic Heroes', 'Tasoloikka', 3, 9),
('Space Chimps', 'Tasoloikka', 3, 9),
('Spyro: A Hero´s Tail', 'Tasoloikka', 3, 9),
('Star Wars Episode III: Revenge of the Sith', 'Toiminta', 12, 9),
('State of Emergency', 'Tappelu', 18, 9),
('Street Hoops', 'Urheilu', 15, 9),
('Tak 2: The Staff of Dreams', 'Toiminta / Seikkailu', 3, 9),
('Tekken Tag Tournament', 'Taistelu', 11, 9),
('Terminator 3: Rise of the Machines', 'First Person Shooter / Toiminta', 16, 9),
('Terminator: Dawn of Fate', 'Toiminta', 11, 9),
('The Getaway', 'Toiminta / Seikkailu', 18, 9),
('The Getaway: Black Monday', 'Toiminta / Seikkailu', 18, 9),
('The Legend of Spyro: A New Beginning', 'Toiminta', 3, 9),
('The Legend of Spyro: Dawn of the Dragon', 'Toiminta / Seikkailu', 7, 9),
('The Legend of Spyro: the Eternal Night', 'Toiminta / Seikkailu', 7, 9),
('The Lord of the Rings: The Two Towers', 'Toiminta / Hack and Slash', 12, 9),
('The Matrix: Path of Neo', 'Toiminta / Seikkailu', 15, 9),
('The Simpsons Videopeli', 'Toiminta / Seikkailu', 12, 9),
('The Sims 2: Autiosaari', 'Simulaatio', 12, 9),
('The Sims 2: Lemmikkielämää', 'Simulaatio', 11, 9),
('The Sims: Ryntää Raitille', 'Simulaatio', 7, 9),
('The Warriors', 'Toiminta / Seikkailu', 18, 9),
('Tiger Woods PGA Tour 07', 'Urheilu', 3, 9),
('TimeSplitters Future Perfect', 'First Person Shooter', 18, 9),
('Tom Clancy´s Splinter Cell: Double Agent', 'Toiminta / Seikkailu / Third Person Shooter', 18, 9),
('Toca Race Driver', 'Ajopeli', 11, 9),
('Tom Clancy´s Splinter Cell: Pandora Tomorrow', 'Toiminta / Seikkailu / Third Person Shooter', 12, 9),
('Tomb Raider: Underworld', 'Toiminta / Seikkailu', 16, 9),
('Tony Hawk´s Downhill Jam', 'Urheilu', 3, 9),
('Tony Hawks Pro Skater 3', 'Urheilu', 12, 9),
('Top Spin', 'Urheilu', 3, 9),
('Toy Story 3', 'Tasoloikka', 3, 9),
('Truecrime: New York City', 'Toiminta / Seikkailu', 18, 9),
('Up', 'Toiminta / Seikkailu', 3, 9),
('Wakeboarding Unleashed Featuring Shaun Murray', 'Urheilu', 3, 9),
('Winter Sports: The Ultimate Challenge 2008', 'Urheilu', 3, 9),
('Woody Woodpecker', 'Tasoloikka', 11, 9),
('Worms 4: Mayhem', 'Strategia', 3, 9),
('WRC World Rally Championship', 'Ajopeli', 3, 9),
('WWI: Aces of The Sky', 'Lentopeli', 3, 9),
('X Games Skateboarding', 'Urheilu', 3, 9),
('X-Men Legends', 'Toimintaroolipeli', 12, 9),
('Alkupolku Englannin kieli, Mysteeri Lontoossa', 'Oppimispeli', 3, 19),
('Ellen Whitaker´s Horse Life', 'Ratsastus', 3, 19),
('Hello Kitty Big City Dreams', 'Seikkailu', 3, 19),
('Petz: My Kitten Family', 'Virtuaalilemmikit', 3, 19),
('Ferrari Challenge Deluxe', 'Ajopeli', 3, 6),
('Mario & Sonic: at the London 2012 Olympic Games', 'Urheilu', 3, 6),
('New Super Mario Bros.Wii', 'Tasoloikka', 3, 6),
('Wii Sport', 'Urheilu', 7, 6),
('2002 Fifa World Cup', 'Urheilu', 3, 7),
('Beyblade: Let It Rip', 'Taistelu', 3, 7),
('Brian Lara Cricket', 'Urheilu', 3, 7),
('Disney Pixar Toy Story Racer', 'Ajopeli', 3, 7),
('FIFA 2001', 'Urheilu', 3, 7),
('Fifa Football 2004', 'Urheilu', 3, 7),
('Scooter Racing', 'Urheilu', 3, 7),
('Spec Ops: Stealth Patrol', 'Ammunta', 13, 7),
('Star Wars Episode I: Jedi Power Battles', 'Toiminta / Hack and Slash', 12, 7),
('The Lost World: Jurassic Park', 'Toiminta', 12, 7),
('Theme Park World', 'Simulaatio', 3, 7),
('This is Football 2', 'Urheilu', 3, 7),
('Resident Evil ', 'Selviytymiskauhu', 18, 7),
('Black', 'First Person Shooter', 16, 9),
('Colin McRae Rally 04', 'Ajopeli', 3, 9),
('Cricket 2004', 'Urheilu', 3, 9),
('Devil Kings', 'Hack and Slash', 12, 9),
('Dragon Ball Z: Budokai Tenkaichi', 'Taistelu', 12, 9),
('Drome Racers', 'Ajopeli', 3, 9),
('Enthusia: Professional Racing', 'Ajopeli / Simulaatio', 3, 9),
('FlatOut 2', 'Ajopeli', 12, 9),
('Girl Zone', 'Simulaatio', 12, 9),
('Gran Turismo 4 Prologue', 'Ajopeli / Simulaatio', 12, 9),
('Ihmeperhe', 'Toiminta / Seikkailu', 7, 9),
('Jak 3', 'Tasoloikka / Toiminta / Seikkailu', 12, 9),
('Lara Croft Tomb Raider: Anniversary', 'Toiminta / Seikkailu', 16, 9),
('Lara Croft Tomb Raider: Legend', 'Toiminta / Seikkailu', 12, 9),
('Lara Croft Tomb Raider: The Angel of Darkness', 'Toiminta / Seikkailu', 12, 9),
('Medal of Honor: European Assault', 'First Person Shooter', 16, 9),
('Medal of Honor: Rising Sun', 'First Person Shooter', 12, 9),
('Naruto: Ultimate Ninja', 'Taistelu', 12, 9),
('Oni', 'Toiminta', 15, 9),
('Onimusha Blade Warriors', 'Taistelu', 12, 9),
('Psychonauts', 'Tasoloikka', 12, 9),
('Ratchet: Gladiator', 'Tasoloikka', 3, 9),
('Red Dead Revolver', 'Toiminta / Seikkailu', 16, 9),
('Samurai Warriors 2: Xtreme Legends', 'Hack and Slash', 12, 9),
('Samurai Warriors 2: Empires', 'Hack and Slash', 12, 9),
('Spy vs Spy', 'Tasoloikka', 12, 9),
('SSX 3', 'Urheilu', 3, 9),
('Star Wars: Battlefront 2', 'Toiminta', 12, 9),
('Super Monkey Ball Adventure', 'Tasoloikka', 3, 9),
('Suzuki Super-Bikes II: Riding Challenge', 'Ajopeli', 3, 9),
('The Spiderwick Chronicles', 'Toiminta / Seikkailu', 3, 9),
('V-Rally 3', 'Ajopeli', 3, 9),
('Zathura', 'Toiminta / Seikkailu', 7, 9);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `pelit`
--
ALTER TABLE `pelit`
  ADD PRIMARY KEY (`pelit_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `pelit`
--
ALTER TABLE `pelit`
  MODIFY `pelit_id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=839;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
