INSERT INTO genre (tyylilaji) VALUES
('Ajopeli'),
('Ammunta'),
('Arcade'),
('First Person Action'),
('First Person Shooter'),
('Hack and Slash'),
('Hiiviskelypeli'),
('Inter Active'),
('Karaoke'),
('Kauhu'),
('Kokoelma'),
('Lentopeli'),
('MMORPG'),
('Musiikki'),
('Party Game'),
('Piirustus'),
('Puzzle'),
('Pyöräily'),
('Rail Shooter'),
('Ralli'),
('Ratsastus'),
('Reaaliaikainen Strategiapeli'),
('Rooli'),
('Seikkailu'),
('Selviytymiskauhu'),
('Simulaatio'),
('Strategia'),
('Taistelu'),
('Tanssi'),
('Tappelu'),
('Tasoloikka'),
('Third Person Shooter'),
('Toiminta'),
('Urheilu'),
('Toimintaroolipeli'),
('Tietokilpailu'),
('Oppimispeli'),
('Virtuaalilemmikit');